// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'database_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1MhLtbaHdpzzjkPZBi5nShe8Xx7Xr_Eg',
    appId: '1:82770132102:web:5563dd28322205ce9a6507',
    messagingSenderId: '82770132102',
    projectId: 'journey-38393',
    authDomain: 'journey-38393.firebaseapp.com',
    storageBucket: 'journey-38393.firebasestorage.app',
    measurementId: 'G-1K8D79VN5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVkddyAo3HOAFEDfILOCLaJF-5bZJvYsQ',
    appId: '1:82770132102:android:e36bb870f9247cc99a6507',
    messagingSenderId: '82770132102',
    projectId: 'journey-38393',
    storageBucket: 'journey-38393.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVSWIxeqIvdei9x3EowV2A0toxdoEJbvI',
    appId: '1:82770132102:ios:13f250ca11c55dae9a6507',
    messagingSenderId: '82770132102',
    projectId: 'journey-38393',
    storageBucket: 'journey-38393.firebasestorage.app',
    iosBundleId: 'com.example.journey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVSWIxeqIvdei9x3EowV2A0toxdoEJbvI',
    appId: '1:82770132102:ios:13f250ca11c55dae9a6507',
    messagingSenderId: '82770132102',
    projectId: 'journey-38393',
    storageBucket: 'journey-38393.firebasestorage.app',
    iosBundleId: 'com.example.journey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1MhLtbaHdpzzjkPZBi5nShe8Xx7Xr_Eg',
    appId: '1:82770132102:web:3ebca000e417df8e9a6507',
    messagingSenderId: '82770132102',
    projectId: 'journey-38393',
    authDomain: 'journey-38393.firebaseapp.com',
    storageBucket: 'journey-38393.firebasestorage.app',
    measurementId: 'G-R1M9CZRN4K',
  );
}
